import '../models/skill_assessment.dart';

/// Static adaptive-assessment question bank: 8 categories, each with 4
/// easy + 4 medium + 4 hard questions. `correctIndex` always points at
/// option 0 here for readability — [PresentedQuestion] shuffles the
/// options before a question is shown to the user.
final List<AssessmentCategory> kAssessmentCategories = [
  AssessmentCategory(
    key: 'programming',
    label: 'Programming',
    description: 'Core coding concepts, data structures, and complexity',
    questions: [
      const AssessmentQuestion(
        id: 'prog_e1',
        text: 'What does a `for` loop primarily allow you to do?',
        options: [
          'Repeat a block of code',
          'Define a variable type',
          'Import a library',
          'Handle exceptions',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'prog_e2',
        text:
            'Which symbol commonly ends a statement in languages like Java or C#?',
        options: ['Semicolon (;)', 'Colon (:)', 'Hash (#)', 'Ampersand (&)'],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'prog_e3',
        text:
            'What is the term for a named, reusable block of code that performs a task?',
        options: ['Function', 'Variable', 'Loop', 'Comment'],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'prog_e4',
        text: 'Which data type stores true/false values?',
        options: ['Boolean', 'String', 'Integer', 'Float'],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'prog_m1',
        text:
            'What is the time complexity of searching in a balanced binary search tree?',
        options: ['O(log n)', 'O(n)', 'O(n^2)', 'O(1)'],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'prog_m2',
        text:
            'Which principle states a class should have only one reason to change?',
        options: [
          'Single Responsibility Principle',
          'Open/Closed Principle',
          'Liskov Substitution Principle',
          'Dependency Inversion Principle',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'prog_m3',
        text: 'What does "recursion" mean in programming?',
        options: [
          'A function calling itself',
          'A loop that never ends',
          'A variable that changes type',
          'A class inheriting from itself',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'prog_m4',
        text: 'Which data structure uses LIFO (last in, first out) ordering?',
        options: ['Stack', 'Queue', 'Linked list', 'Array'],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'prog_h1',
        text: 'What is the main benefit of a hash map over a list for lookups?',
        options: [
          'Average O(1) lookup time',
          'Guaranteed order of elements',
          'Always lower memory usage',
          'Simpler syntax',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'prog_h2',
        text: 'In concurrent programming, what is a race condition?',
        options: [
          'Threads accessing shared data with an unpredictable outcome',
          'A loop that runs too fast',
          'A function that never terminates',
          'A memory leak caused by unused variables',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'prog_h3',
        text:
            'Which technique avoids redundant computation by storing previously computed results?',
        options: [
          'Memoization',
          'Polymorphism',
          'Serialization',
          'Garbage collection',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'prog_h4',
        text: 'What does Big O notation primarily describe?',
        options: [
          'How run time or space grows with input size',
          'The exact number of seconds a program takes',
          'The number of lines of code',
          "The programming language's syntax rules",
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
    ],
  ),
  AssessmentCategory(
    key: 'database',
    label: 'Database management',
    description: 'SQL, schema design, and transaction fundamentals',
    questions: [
      const AssessmentQuestion(
        id: 'db_e1',
        text: 'What does SQL stand for?',
        options: [
          'Structured Query Language',
          'Simple Query Logic',
          'Sequential Query List',
          'Standard Question Language',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'db_e2',
        text: 'Which SQL statement retrieves data from a table?',
        options: ['SELECT', 'GET', 'FETCH', 'PULL'],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'db_e3',
        text: 'What is a primary key used for?',
        options: [
          'Uniquely identifying a row in a table',
          'Encrypting a column',
          "Formatting a table's display",
          'Connecting to the database server',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'db_e4',
        text: 'Which of these is a relational database?',
        options: ['MySQL', 'Photoshop', 'Docker', 'Figma'],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'db_m1',
        text: 'What does a foreign key represent?',
        options: [
          "A link to another table's primary key",
          'A password for the database',
          'A backup copy of a table',
          'An index on the primary key',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'db_m2',
        text: 'What is database normalization mainly used for?',
        options: [
          'Reducing data redundancy and improving integrity',
          'Making queries run in parallel',
          'Encrypting stored data',
          'Increasing table size for performance',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'db_m3',
        text: 'Which SQL clause filters grouped results?',
        options: ['HAVING', 'WHERE', 'GROUP', 'FILTER'],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'db_m4',
        text: 'Which join returns only matching rows from both tables?',
        options: ['INNER JOIN', 'LEFT JOIN', 'FULL OUTER JOIN', 'CROSS JOIN'],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'db_h1',
        text: 'Which of these is NOT one of the ACID transaction properties?',
        options: ['Scalability', 'Atomicity', 'Consistency', 'Durability'],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'db_h2',
        text: 'What is the purpose of a database index?',
        options: [
          'Speed up retrieval at the cost of storage and slower writes',
          'Guarantee data is never duplicated',
          'Automatically normalize a table',
          'Encrypt sensitive columns',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'db_h3',
        text:
            'What isolation level prevents dirty reads but allows non-repeatable reads?',
        options: [
          'Read Committed',
          'Read Uncommitted',
          'Serializable',
          'Repeatable Read',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'db_h4',
        text: 'What is database sharding?',
        options: [
          'Splitting a database horizontally across multiple servers',
          'Encrypting a database column',
          'Merging two tables into one',
          'Creating a backup snapshot',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
    ],
  ),
  AssessmentCategory(
    key: 'networking',
    label: 'Networking',
    description: 'Protocols, addressing, and how traffic moves',
    questions: [
      const AssessmentQuestion(
        id: 'net_e1',
        text: 'What does IP stand for in "IP address"?',
        options: [
          'Internet Protocol',
          'Internal Program',
          'Input Port',
          'Interface Process',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'net_e2',
        text:
            'Which device forwards data between different networks based on IP address?',
        options: ['Router', 'Switch', 'Hub', 'Modem'],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'net_e3',
        text: 'What does "LAN" stand for?',
        options: [
          'Local Area Network',
          'Large Area Node',
          'Linked Access Network',
          'Logical Address Number',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'net_e4',
        text: 'Which protocol is used to send email?',
        options: ['SMTP', 'HTTP', 'FTP', 'DNS'],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'net_m1',
        text: 'What is the main purpose of DNS?',
        options: [
          'Translating domain names into IP addresses',
          'Encrypting network traffic',
          'Assigning MAC addresses',
          'Compressing data packets',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'net_m2',
        text: 'Which OSI layer routes packets between networks?',
        options: [
          'Network layer',
          'Transport layer',
          'Data link layer',
          'Session layer',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'net_m3',
        text: 'What does a subnet mask determine?',
        options: [
          "Which part of an IP address is network vs host",
          'The physical speed of a network cable',
          'The MAC address of a device',
          'The DNS server to use',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'net_m4',
        text: 'What is the default port number for HTTPS?',
        options: ['443', '80', '21', '25'],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'net_h1',
        text: 'What problem does NAT primarily solve?',
        options: [
          'Letting multiple devices share one public IP address',
          'Encrypting all network traffic',
          'Assigning domain names to IP addresses',
          'Load balancing across servers',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'net_h2',
        text: "What is the purpose of TCP's three-way handshake?",
        options: [
          'Establishing a reliable connection before data transfer',
          'Encrypting the payload of each packet',
          'Compressing data before sending',
          'Choosing the fastest route between two hosts',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'net_h3',
        text: 'What does BGP primarily manage?',
        options: [
          'Routing between autonomous systems on the internet',
          'Assigning private IP addresses on a LAN',
          'Encrypting DNS queries',
          'Load-balancing traffic on a single switch',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'net_h4',
        text: 'What is a VLAN used for?',
        options: [
          'Logically segmenting a network into separate broadcast domains',
          'Physically separating network cables',
          'Encrypting wireless traffic',
          'Assigning static IP addresses automatically',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
    ],
  ),
  AssessmentCategory(
    key: 'cybersecurity',
    label: 'Cybersecurity',
    description: 'Threats, defenses, and security best practices',
    questions: [
      const AssessmentQuestion(
        id: 'sec_e1',
        text: 'What is phishing?',
        options: [
          'Tricking someone into revealing sensitive info via deceptive messages',
          'A type of firewall',
          'A method of encrypting files',
          'A network speed test',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'sec_e2',
        text: 'What does a firewall primarily do?',
        options: [
          'Filters incoming and outgoing traffic based on rules',
          'Speeds up internet connections',
          'Stores passwords securely',
          'Backs up files automatically',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'sec_e3',
        text: 'What is a strong password practice?',
        options: [
          'Using a long, unique passphrase for each account',
          'Reusing the same password everywhere',
          'Writing passwords on a sticky note',
          'Using your name and birthdate',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'sec_e4',
        text: 'What does "malware" refer to?',
        options: [
          'Software designed to harm or exploit systems',
          'A tool for optimizing databases',
          'A type of network cable',
          'A backup utility',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'sec_m1',
        text: 'What is two-factor authentication (2FA)?',
        options: [
          'Verifying identity using two different types of credentials',
          'Using two passwords for the same account',
          'Logging in from two devices at once',
          'Encrypting data twice',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'sec_m2',
        text: 'What is a common purpose of a VPN?',
        options: [
          "Encrypting traffic and masking a device's IP address",
          'Speeding up local file transfers',
          'Blocking all incoming connections',
          'Managing DNS records',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'sec_m3',
        text: 'What is SQL injection?',
        options: [
          'Inserting malicious SQL through user input to manipulate a database',
          'A method to back up a database',
          'A way to optimize SQL queries',
          'A type of database index',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'sec_m4',
        text: 'What does the principle of least privilege mean?',
        options: [
          'Giving users only the access they need to do their job',
          'Giving all users admin access by default',
          'Encrypting only the most sensitive files',
          'Disabling all user accounts',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'sec_h1',
        text: 'What is a zero-day vulnerability?',
        options: [
          'A flaw exploited before the vendor releases a fix',
          'A vulnerability that takes zero days to patch',
          'A bug found on day zero of development',
          'An outdated antivirus signature',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'sec_h2',
        text: 'What does a SIEM system primarily do?',
        options: [
          'Aggregate and analyze security logs to detect threats',
          'Encrypt files at rest',
          'Manage employee payroll',
          'Provision new servers automatically',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'sec_h3',
        text: 'In a penetration test, what does "privilege escalation" mean?',
        options: [
          'Gaining higher-level access than originally granted',
          "Lowering a user's access rights",
          'Encrypting an admin account',
          'Resetting all passwords',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'sec_h4',
        text: 'What is the purpose of a security incident response plan?',
        options: [
          'Defining steps to detect, contain, and recover from a breach',
          'Designing the company logo',
          'Scheduling routine software updates',
          'Managing marketing campaigns',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
    ],
  ),
  AssessmentCategory(
    key: 'data_analytics',
    label: 'Data analytics',
    description: 'Statistics, visualization, and drawing insight from data',
    questions: [
      const AssessmentQuestion(
        id: 'data_e1',
        text: 'What is the mean of a data set?',
        options: [
          'The average of all values',
          'The most frequently occurring value',
          'The middle value when sorted',
          'The difference between max and min',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'data_e2',
        text: 'Which chart type is best for showing trends over time?',
        options: ['Line chart', 'Pie chart', 'Scatter plot', 'Histogram'],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'data_e3',
        text: 'What does "data cleaning" involve?',
        options: [
          'Fixing or removing incorrect, incomplete, or duplicate data',
          'Deleting an entire dataset',
          'Encrypting sensitive data',
          'Visualizing data in charts',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'data_e4',
        text: 'What is a "dataset"?',
        options: [
          'A structured collection of related data',
          'A single number',
          'A type of chart',
          'A programming loop',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'data_m1',
        text: 'What does correlation measure?',
        options: [
          'The strength and direction of a relationship between two variables',
          'The average of a dataset',
          'The total count of records',
          'The standard deviation',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'data_m2',
        text: 'What is the purpose of a pivot table?',
        options: [
          'Summarizing and reorganizing data to reveal insights',
          'Encrypting spreadsheet data',
          'Writing SQL queries',
          'Creating a database schema',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'data_m3',
        text: 'What does an outlier represent in a dataset?',
        options: [
          'A data point that differs significantly from other observations',
          'The most common value',
          'The median of the dataset',
          'A missing value',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'data_m4',
        text: 'Which best describes "data visualization"?',
        options: [
          'Representing data graphically to make patterns easier to understand',
          'Encrypting a dataset for storage',
          'Removing duplicate rows from a table',
          'Writing a database schema',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'data_h1',
        text: 'What is the main risk of overfitting a predictive model?',
        options: [
          'It performs well on training data but poorly on new data',
          'It runs too slowly to be useful',
          'It uses too little data to train',
          'It cannot be visualized',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'data_h2',
        text: 'What does A/B testing help determine?',
        options: [
          'Which of two variants performs better on a measurable outcome',
          'The average value of a dataset',
          'How to clean missing data',
          "How to encrypt a user's data",
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'data_h3',
        text:
            'What is the purpose of dimensionality reduction techniques like PCA?',
        options: [
          'Reducing the number of variables while preserving key information',
          'Increasing the size of a dataset',
          'Encrypting data for privacy',
          'Sorting data alphabetically',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'data_h4',
        text: 'In statistics, what does a p-value help assess?',
        options: [
          'The probability of results this extreme under the null hypothesis',
          'The average of a sample',
          'The size of a dataset',
          'The correlation coefficient directly',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
    ],
  ),
  AssessmentCategory(
    key: 'cloud_computing',
    label: 'Cloud computing',
    description: 'Cloud services, deployment models, and scaling',
    questions: [
      const AssessmentQuestion(
        id: 'cloud_e1',
        text: 'What does "cloud computing" mean?',
        options: [
          'Delivering computing services like storage and servers over the internet',
          'Storing files only on a local hard drive',
          'A type of programming language',
          'A network cable standard',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'cloud_e2',
        text: 'Which of these is a major public cloud provider?',
        options: [
          'Amazon Web Services',
          'Microsoft Word',
          'Adobe Photoshop',
          'Notepad',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'cloud_e3',
        text: 'What does SaaS stand for?',
        options: [
          'Software as a Service',
          'Server as a Storage',
          'System as a Solution',
          'Security as a Standard',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'cloud_e4',
        text: 'What is a main benefit of cloud storage over local storage?',
        options: [
          'Access files from anywhere with an internet connection',
          'It always loads faster than a local disk',
          'It never requires a password',
          'It works without internet access',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'cloud_m1',
        text: 'What does "auto-scaling" allow a cloud application to do?',
        options: [
          'Automatically add or remove resources based on demand',
          'Automatically back up data every second',
          'Automatically encrypt all traffic',
          'Automatically translate the UI',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'cloud_m2',
        text: 'What is the difference between IaaS and PaaS?',
        options: [
          'IaaS provides raw infrastructure; PaaS gives a platform to build on',
          'IaaS is free while PaaS is paid',
          'PaaS only runs on-premises',
          'IaaS is only for storage',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'cloud_m3',
        text: 'What is a "region" in cloud computing?',
        options: [
          'A geographic area containing multiple data centers',
          'A single physical server',
          'A type of firewall rule',
          'A billing currency',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'cloud_m4',
        text: 'What is the purpose of a load balancer?',
        options: [
          'Distributing incoming traffic across multiple servers',
          'Encrypting stored data',
          'Compressing files before upload',
          'Monitoring employee activity',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'cloud_h1',
        text: 'What is the main advantage of a multi-cloud strategy?',
        options: [
          'Avoiding vendor lock-in and increasing resilience',
          'Reducing the number of cloud skills needed',
          'Guaranteeing lower costs than a single provider',
          'Eliminating the need for monitoring',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'cloud_h2',
        text: 'What does "infrastructure as code" (IaC) enable?',
        options: [
          'Provisioning infrastructure through machine-readable config files',
          'Writing infrastructure documentation in a word processor',
          'Running code only on physical servers',
          'Encrypting source code automatically',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'cloud_h3',
        text:
            "What is a key customer responsibility under the shared responsibility model?",
        options: [
          'Securing their data, identities, and app configurations',
          'Physically securing the data center',
          "Patching the provider's hypervisor",
          "Managing the provider's network hardware",
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'cloud_h4',
        text:
            'What problem do container orchestration tools like Kubernetes solve?',
        options: [
          'Automating deployment, scaling, and management of containers',
          'Writing application source code',
          'Designing database schemas',
          'Encrypting network traffic',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
    ],
  ),
  AssessmentCategory(
    key: 'software_testing',
    label: 'Software testing',
    description: 'QA fundamentals, test types, and automation',
    questions: [
      const AssessmentQuestion(
        id: 'test_e1',
        text: 'What is the purpose of software testing?',
        options: [
          'Finding defects and verifying the software works as expected',
          'Writing new features faster',
          'Designing the user interface',
          'Deploying code to production',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'test_e2',
        text: 'What is a "bug"?',
        options: [
          'A defect that causes software to behave unexpectedly',
          'A new feature request',
          'A type of test plan',
          'A deployment script',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'test_e3',
        text: 'What is unit testing?',
        options: [
          'Testing individual components or functions in isolation',
          'Testing the entire system end-to-end',
          'Testing only the user interface',
          'Testing the deployment pipeline',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'test_e4',
        text: 'What does "manual testing" mean?',
        options: [
          'A person executes test cases without automation tools',
          'Tests run automatically on a schedule',
          'Tests written in a programming language',
          'Testing done only by developers',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'test_m1',
        text: 'What is regression testing used for?',
        options: [
          "Verifying new changes haven't broken existing functionality",
          'Testing only brand new features',
          'Measuring server response time',
          'Testing the installation process only',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'test_m2',
        text: 'What is the difference between black-box and white-box testing?',
        options: [
          'Black-box tests behavior only; white-box tests with code knowledge',
          'Black-box is automated while white-box is manual',
          'Black-box only tests the UI while white-box only tests databases',
          'There is no real difference',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'test_m3',
        text: 'What is the purpose of a test case?',
        options: [
          'Defining steps, inputs, and expected results to verify a behavior',
          'Writing production code',
          'Designing a database schema',
          'Deploying an application',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'test_m4',
        text: 'What does "test coverage" measure?',
        options: [
          'The proportion of code exercised by tests',
          'The number of bugs found in production',
          'The speed of the test suite',
          'The number of testers on a team',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'test_h1',
        text: 'What is the main goal of continuous integration (CI) testing?',
        options: [
          'Automatically running tests on every merge to catch issues early',
          'Manually testing once per release',
          'Testing only after deployment to production',
          'Skipping tests for minor changes',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'test_h2',
        text: 'What is a "flaky test"?',
        options: [
          'A test that passes or fails inconsistently without code changes',
          'A test that always fails',
          'A test with no assertions',
          'A test that runs very slowly',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'test_h3',
        text: 'What is the purpose of mocking in unit tests?',
        options: [
          'Simulating dependencies so a unit can be tested in isolation',
          'Making tests run in production',
          'Replacing the entire test suite',
          'Increasing code coverage artificially',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'test_h4',
        text: 'What does "load testing" evaluate?',
        options: [
          'How a system performs under expected or peak demand',
          'Whether the UI colors meet design specs',
          'Whether the code compiles without errors',
          'Whether documentation is complete',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
    ],
  ),
  AssessmentCategory(
    key: 'communication',
    label: 'Communication & problem-solving',
    description: 'Working with others and reasoning through issues',
    questions: [
      const AssessmentQuestion(
        id: 'comm_e1',
        text: 'What is active listening?',
        options: [
          'Fully concentrating on and understanding what someone says before responding',
          'Speaking as much as possible in a conversation',
          'Multitasking while someone talks',
          'Interrupting to share your opinion quickly',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'comm_e2',
        text:
            'When facing a problem, what is usually the first step in a structured approach?',
        options: [
          'Clearly defining the problem',
          'Implementing a solution immediately',
          'Blaming a team member',
          'Skipping to the final decision',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'comm_e3',
        text: 'What is good practice when giving feedback to a teammate?',
        options: [
          'Being specific, constructive, and respectful',
          'Only pointing out flaws',
          'Giving feedback publicly to embarrass them',
          'Avoiding feedback altogether',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'comm_e4',
        text: 'Why is clear written communication important at work?',
        options: [
          'It reduces misunderstandings and keeps everyone aligned',
          'It makes messages longer',
          'It replaces the need for meetings entirely',
          'It is only useful for emails',
        ],
        correctIndex: 0,
        difficulty: 1,
      ),
      const AssessmentQuestion(
        id: 'comm_m1',
        text: 'What does root cause analysis aim to identify?',
        options: [
          'The underlying reason a problem occurred, not just its symptoms',
          'The first person who noticed the issue',
          'The most expensive part of a project',
          'The newest technology available',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'comm_m2',
        text:
            'In a disagreement with a colleague, what is a constructive approach?',
        options: [
          'Understanding their perspective and finding common ground',
          'Insisting you are right without listening',
          'Escalating immediately to a manager',
          'Ignoring the disagreement entirely',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'comm_m3',
        text:
            'What is the benefit of breaking a large problem into smaller parts?',
        options: [
          'It makes the problem easier to analyze and solve step by step',
          'It guarantees a faster deadline',
          'It removes the need for testing',
          'It eliminates the need for collaboration',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'comm_m4',
        text: 'What is a key element of effective teamwork?',
        options: [
          'Clear roles and open communication among members',
          'Everyone working entirely independently',
          'Avoiding all disagreements',
          'One person making every decision alone',
        ],
        correctIndex: 0,
        difficulty: 2,
      ),
      const AssessmentQuestion(
        id: 'comm_h1',
        text:
            'A project is behind schedule due to a recurring issue. What is the most effective first step?',
        options: [
          'Investigate the root cause before deciding on a solution',
          'Immediately add more people to the project',
          'Extend the deadline without investigation',
          'Blame the tools being used',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'comm_h2',
        text: 'What is a hallmark of effective stakeholder communication?',
        options: [
          "Tailoring the message and detail to the audience's needs",
          'Sending the same detailed technical report to everyone',
          'Avoiding stakeholders until the project is done',
          'Using jargon to sound authoritative',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'comm_h3',
        text:
            'Two proposed solutions both have trade-offs. What is the best approach?',
        options: [
          'Evaluate them against clear criteria like cost, risk, and impact',
          'Choose the option proposed by the most senior person',
          'Flip a coin to save time',
          'Delay the decision indefinitely',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
      const AssessmentQuestion(
        id: 'comm_h4',
        text: 'What best describes "critical thinking" in problem-solving?',
        options: [
          'Objectively analyzing evidence before forming a conclusion',
          'Accepting the first solution that comes to mind',
          'Following instructions without question',
          'Avoiding difficult problems',
        ],
        correctIndex: 0,
        difficulty: 3,
      ),
    ],
  ),
];
